# Generated by Django 6.0.3 on 2026-03-20 09:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_code', models.CharField(max_length=6, unique=True)),
                ('passphrase', models.TextField(blank=True, null=True)),
                ('member_one', models.CharField(blank=True, default='', max_length=50)),
                ('member_two', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiaryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author_name', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('mood_emoji', models.CharField(blank=True, default='', max_length=10)),
                ('is_favourite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='diary.pair')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PresenceStatus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('member_name', models.CharField(max_length=50)),
                ('vibe_emoji', models.CharField(blank=True, default='', max_length=10)),
                ('vibe_text', models.CharField(blank=True, default='', max_length=60)),
                ('is_online', models.BooleanField(default=False)),
                ('timezone_name', models.CharField(default='Asia/Kolkata', max_length=60)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='diary.pair')),
            ],
            options={
                'unique_together': {('pair', 'member_name')},
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reactor_name', models.CharField(max_length=50)),
                ('emoji', models.CharField(default='❤️', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='diary.diaryentry')),
            ],
            options={
                'unique_together': {('entry', 'reactor_name', 'emoji')},
            },
        ),
    ]
